[workspace]
members = [
    "waveshare-touchscreen"
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
embuild = { version = "0.33.1", features = ["espidf"] }
esp-idf-sys = "0.36.1"
esp-idf-svc = "0.51.0"
log = "0.4"
