[build]
target = "xtensa-esp32s3-espidf"

[env]
ESP_IDF_VERSION = "tag:v5.3.4"
# ESP_IDF_SDKCONFIG_DEFAULTS = ""
ESP_IDF_SYS_ROOT_CRATE = "waveshare-touchscreen"

[target.'cfg(target_arch = "xtensa")']
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = []

[unstable]
build-std = ["alloc", "std", "panic_abort"]
build-std-features = ["optimize_for_size"]
