[build]
target = "xtensa-esp32s3-espidf"

[target.'cfg(target_arch = "xtensa")']
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = []

[unstable]
build-std = ["alloc", "std", "panic_abort"]
build-std-features = ["optimize_for_size"]
